- name: DEBIAN | Install GitLab GPG key
  apt_key:
    state: present
    url: https://packages.gitlab.com/gpg.key
  tags:
    - gitlab
    - gitlab-gpg

- name: DEBIAN | Install support packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
      - curl
      - ca-certificates
      - postfix
  tags:
    - gitlab
    - gitlab-packages

- name: DEBIAN | Install GitLab CE
  apt:
    name: gitlab-ce{{ '=' + gitlab_version + gitlab_version_suffix if gitlab_version is defined else '' }}
    state: "{{ 'present' if gitlab_version is defined else 'latest' }}"
    update_cache: yes
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn
  tags:
    - gitlab
    - gitlab-update
