Vagrant.configure(2) do |config|

  config.dns.tld = "dev"
  config.ssh.insert_key = false

  # CentOS 6
  config.vm.define "el6" do |el6|
    el6.vm.box = "samdoran/centos6"
    el6.vm.network "forwarded_port", guest: 80, host: 8080
    el6.vm.network "forwarded_port", guest: 443, host: 8443
    el6.vm.hostname = "gitlab-el6.vagrant.dev"
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end

  # CentOS 7
  config.vm.define "el7" do |el7|
    el7.vm.box = "samdoran/centos7"
    el7.vm.network "forwarded_port", guest: 80, host: 8081
    el7.vm.network "forwarded_port", guest: 443, host: 8444
    el7.vm.hostname = "gitlab-el7.vagrant.dev"
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end

  # Debian 8 (Jessie)
  config.vm.define "deb8" do |deb8|
    deb8.vm.box = "debian/jessie64"
    deb8.vm.network "forwarded_port", guest: 80, host: 8083
    deb8.vm.network "forwarded_port", guest: 443, host: 8447
    deb8.vm.hostname = "gitlab-deb8.vagrant.dev"
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end

  # Ubuntu 12.04
  config.vm.define "ub12" do |ub12|
    ub12.vm.box = "ubuntu/precise64"
    ub12.vm.network "forwarded_port", guest: 80, host: 8082
    ub12.vm.network "forwarded_port", guest: 443, host: 8445
    ub12.vm.hostname = "gitlab-ub12.vagrant.dev"
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end

  # Ubuntu 14.04
  config.vm.define "ub14" do |ub14|
    ub14.vm.box = "ubuntu/trusty64"
    ub14.vm.network "forwarded_port", guest: 80, host: 8084
    ub14.vm.network "forwarded_port", guest: 443, host: 8446
    ub14.vm.hostname = "gitlab-ub14.vagrant.dev"
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
